name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        
    - run: yarn upgrade
    - run: yarn run browserslist --update-db 
    - run: yarn
    - run: yarn run build --prod
    
    - name: Publish to github pages
      shell: bash
      run: |
        TEMP_DIR=$(mktemp -d)
        mv "./CNAME" "$TEMP_DIR"
        mv "./dist/open-unicode-converter" "$TEMP_DIR"
        git switch -c "gh-pages"
        git fetch
        git reset --hard origin/gh-pages
        rm -rf *
        mv "$TEMP_DIR/dist/"* .
        git config user.email "srineshnisala@gmail.com"
        git config user.name "s1n7ax"
        git add .
        git commit -m "chore: published at $(date)"
        git pull -r origin "gh-pages"
        git push origin "gh-pages"
